[tool.poetry]
name = "kayak"
version = "0.2.7"
description = "kayak is a ksqlDB TUI (text user interface)"
authors = ["Saúl Piña <sauljabin@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/sauljabin/kayak"
repository = "https://github.com/sauljabin/kayak"
documentation = "https://github.com/sauljabin/kayak"
keywords = ["kafka", "kayak"]
classifiers = [
    "Environment :: Console",
    "Operating System :: MacOS",
    "Operating System :: Unix"
]
include = [
    "LICENSE",
]
packages = [
    { include = "kayak" },
]

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13"
click = "^8"
httpx = {extras = ["http2"], version = "^0"}
pyfiglet = "*"
textual = "*"

[tool.poetry.dev-dependencies]
toml = "*"
pre-commit = "*"
ruff = "*"
black = "*"
mypy = "*"
types-attrs = "*"
changeloggh = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
kayak = "kayak.app:main"
kyk = "kayak.app:main"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100