[tool.poetry]

name = "omnicloud-airport"
version = "0.0.0-dev03"
description = "platform for interacting with omnicloud"
keywords = ["omnicloud", "supercloud", "multicloud", "cloud computing", "migration"]
authors = ["Iurii Tarasenko <iurii@omnicloud.world>"]
readme = "README.md"
packages = [{include = "omnicloud"}]

homepage = "https://omnicloud.world/airport"
repository = "https://github.com/omnicloudworld/py.airport"
documentation = "https://docs.omnicloud.world/py-airport"

classifiers = [
    "Programming Language :: Python :: 3.10",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License"
]


[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
duty = "^0.9.0"
ipykernel = "^6.22.0"
pylint = "^2.17.0"
flake8 = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
