[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vonixsync"
version = "1.0.9"
description = "Database syncronizer"
authors = [{name = "Victor Leone", email = "victor@vonix.com"}]
maintainers = [
  {name = "Luiz", email = "luiz@vonix.com.br"},
  {name = "Vonix", email = "contato@vonix.com.br"},
]
readme = "README.md"
requires-python = ">=3.9"
keywords = ["syncronizer", "vonix"]
license =  {file = "LICENSE"}

classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Environment :: MacOS X"  
]

dependencies = [
"requests>=2.28.2",
"SQLAlchemy>=2.0.6",
"asyncpg>=0.27.0",
"psycopg2-binary>=2.9.5",
"aiohttp>=3.8.4",
"PyJWT>=2.6.0",
"mysql-connector-python>=8.0.32"
]

[project.urls]
repository = "https://github.com/vonix/vonix-py-sync"