[tool.poetry]
name = "fastdem"
version = "0.4.0"
description = ""
authors = ["wanqiang.liu <wanqiang.liu@freetech.com>"]
readme = "README.md"

[tool.poetry.scripts]
fastdem = "fastdem.__main__:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = { extras = ["all"], version = "^0.7.0" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
