[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.2.2",
    "mypy>=1.1.1",
    "black>=23.1.0",
    "pylint>=2.17.0",
    "isort>=5.12.0",
    "pytest-asyncio>=0.21.0",
]

[tool.pdm.scripts]
test = "pytest"
sort = "isort ."
lint = "black ."

[project]
name = "richillcapital-http"
version = "0.1.2"
description = ""
authors = [
    { name = "Mengsyue Amao Tsai", email = "mengsyue.tsai@outlook.com" },
]
dependencies = [
    "aiohttp>=3.8.4",
    "asyncio>=3.4.3",
]
requires-python = ">=3.11"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"
