[tool.poetry]
name = "mokebetoolzxp"
version = "2.0.0"
description = ""
authors = ["mg25683 <maciek.gluszak6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
