[tool.poetry]
name = "latexvm"
version = "0.1.5"
description = ""
authors = ["Ochawin Apichattakul"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sympy = "^1.11.1"
antlr4-python3-runtime = "4.10"
timeout-decorator = "^0.5.0"

[tool.poetry.group.test.dependencies]
pytest-xdist = "^3.2.1"
pytest-cov = "^4.0.0"
pre-commit = "^3.1.1"
pytest = "^7.2.2"
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
