[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lava-engine"
version = "0.1.0"
authors = [
    { name = "Revitalize", email = "boxeigit@gmail.com" },
]
description = "A powerful ðŸš€and simple ðŸ§”ðŸ»â€â™‚ï¸ terminal ðŸ’» game engine"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/RevitalizeStudio/Lava"
"Bug Tracker" = "https://github.com/RevitalizeStudio/Lava/issues"