[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "getfast"
version = "1.0.0"
authors = [
  { name="wd021", email="getfastdeveloper@gmail.com" },
]
description = "A small example package"
readme = "README.md"

[project.urls]
"Homepage" = "https://getfast.dev"
